sudo: false
language: python
# coverage is broken for 3.2
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6
install:
  - pip install -r requirements.txt
  - pip install codecov
script:
  - nosetests --with-coverage
after_success:
  - codecov
notifications:
  email:
    on_success: never
    on_filaure: always
