sudo: false
language: python
# coverage is broken for 2.x-3.2, typing only supported in 3.5+
python:
  - 3.5
  - 3.6
install:
  - pip install -r requirements.txt
  - pip install codecov
script:
  - nosetests --with-coverage
after_success:
  - codecov
notifications:
  email:
    on_success: never
    on_filaure: always
